### ISSUE TITLE
Rebranding from `omniscidb` to `heavydb`

### ISSUE THREAD

**Issue by tupui** [conda-forge/omniscidb-feedstock#96]
In #93 we started to move from `omniscidb` to `heavydb`. Ultimately, the feedstock will be archived and replaced by https://github.com/conda-forge/staged-recipes/pull/18691

By working on the new feedstock we had too many issues we could not resolve in time. Hence, we decided to proceed here since the CI behaves differently and is working as expected.

Still, it is the same package underneath and we are not using this as a gateway to push something else.

The plan is:

1. Merge #93: lack windows support and DBE packages (`heavydbe`, `pyheavydbe`).
2. Fix remaining issues in the new feedstock  https://github.com/conda-forge/staged-recipes/pull/18691
3. Merge it.
4. Archive this feedstock.

**Comment by xhochy** [comment]
Archiving this now.
